[package]
name = "pauliopt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pauliopt"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.22.0"
ndarray = "0.16.1"
lazy_static = "1.5.0"

